### ISSUE TITLE
Add Ticket class to increase abstraction exposure

### ISSUE THREAD

**Issue by johnrwolfe** [johnrwolfe/CarPark#4]
Originally discarded because it was not needed to make the application work, a Ticket class may add enough value on the “exposing abstractions” front to warrant its presence in the class model.  Whether it has an interesting lifecycle is unclear, as a status attribute is likely sufficient to capture the pertinent information:
- Issued
- Awaiting Collection
- Collected
- Inserted

Several associations would be useful:
1. EntryStand 1:1 issued by; Established when a ticket is issued and never removed.
2. Stay 1:1 identifies; Established when an instance of Stay is created and never removed.
3. PaymentMachine 1c:1c inserted into; Established when a ticket is inserted into a payment machine and removed when it is collected from the machine.
4. ExitStand 1c:1c inserted into; Established when a ticket is inserted into an exit stand and never removed because once inserted into an exit stand the ticket is never returned to the driver.

Associations (2) and (4) eliminate the need for the current association between Stay and ExitStand, providing more clarity on the class model regarding the processing of an exit for a stay.

Given the associations described above, it seems acceptable to use 'Awaiting Collection', 'Collected', and 'Inserted' in all applicable cases without adding separate values to distinguish the machine involved.

**Comment by SoftImp** [comment]
Now this is interesting, because it aligns with how I had thought of including and using a TICKET class.  In fact in my original modelling of the car park TICKET was the central abstraction.  Everything you have described here seems appropriate to me.  So, by all means resolve the issue before doing any GUI stuff.

**Comment by johnrwolfe** [comment]
![image](https://user-images.githubusercontent.com/2199907/81456019-da550f80-9145-11ea-8020-f3b8a7235116.png)

**Comment by SoftImp** [comment]
This actual effort showing a 'not-insignificant' change to a mature model is very useful for talking to customers about 'the cost of change'.  Not only that the influence/extent of the change is quite apparent and bounded.  

I can easily imagine attempting to make such a change in a 'code-only' effort!  One might never be sure that it is 'bounded' appropriately in terms of extent/influence, let alone the effort involved.  I could see even the best of programmers taking at least a whole day without fully testing whatever they changed.
