### ISSUE TITLE
Client registration, creation

### ISSUE THREAD

**Issue by johnrwolfe** [johnrwolfe/CarPark#61]
### Issue
Presently, instances of EntryStand, ExitStand, and PaymentMachine are created by an initialization function when the application is started.  Browser-based clients must the use the identifier (location) for a pre-existing peripheral.  Worse, the Operator Console client is hard-coded to support only the "North" Entry Stand and the "Lane 1" Exit Stand.
### Solution
To make the system more flexible and more realistic, the following changes must be made.
1. Add "Register" and "Unregister" messages to the EntryStand, ExitStand, and PaymentMachine interface definitions.  These messages carry a single parameter, "Location" and flow to the provider (the CarparkControl component).
2. Add "Register" and "Unregister" messages to the OperatorConsole interface definition.  These carry two parameters, "Peripheral" (indicating EntryStand or ExitStand), and "Location" and flow from the provider (CarparkControl) to the OperatorConsole.
3. Remove the creation of EntryStand, ExitStand, and PaymentMachine from Initialization/CreatePEIs.
4. Add class-based Create() and Remove() operations to EntryStand, ExitStand, and PaymentMachine, accepting a "Location" parameter.  These operations are responsible for creating/deleting and linking/unlinking an instance of the class, and in the case of EntryStand and ExitStand, sending the OperatorConsole::Register/Unregister messages.
5. Add port activities for the incoming messages on CarparkControl to invoke the appropriate Create()/Remove() operations.
6. Add domain functions and port activities invoking them for the new incoming messages on the OperatorConsole shell component.
7. Add hand-written Java classes for the new messages.
8. Modify `<client>.java` and `<client>MsgController.java` to handle the new messages.
9. Modify `<client>.js` to send the "Register" message when the "Connect" button is poked and the "Unregister" message when the "Disconnect" button is pushed.
10. Modify OperatorConsole.html/js to make use of the incoming "Register" and "Unregister" messages to allocate/deallocate sections for entry/exit stands on the page.  Consider using Vue components to represent entry and exit stands so they can easily be instantiated and removed as necessary.
### Notes
1. For operation with browser-based clients, all peripheral instances within CarparkControl are created through the registration process described above.  However, the existing section of Initialization/CreaetPEIs that creates peripheral instances should be harvested and saved in another function so that these PEIs can be used with the testbench or for interactive testing with Verifier.  Some additional work is then required to ensure the testbench continues to operate correctly.
2. See the Vue Essentials Cheat [Sheet](https://www.vuemastery.com/pdf/Vue-Essentials-Cheat-Sheet.pdf) and Vue [Guide](https://vuejs.org/v2/guide/) for guidance on reusable components and dynamically populating lists (e.g., Entry/Exit Stand display areas).

**Comment by amullarney** [comment]
Register more important than Unregister - at least, initially?
Response to duplicate "Location" parameter?

**Comment by johnrwolfe** [comment]
Yes, I suggest getting Register working first and then move on to Unregister.  We need them both.
For now, we will allow the registration of duplicate clients, so the Carpark application will simply ignore subsequent Register messages for an instance of a peripheral that already exists.  While this makes no sense for entry/exit stands and payment machines in a real deployment of the Carpark system, it will be useful for demonstration purposes for other applications to have the ability to show multiple identical clients, say on different machines, both receiving the same messages from the server and both with the ability to send messages to the server.
